#!/usr/bin/env bash

# Show info and run flatpak apps with fzf
#   flatapp [arguments]

flatpak_preview() {
	app="$(echo "${1}" | awk -F'\t' '{print $2}')"
	flatpak info "${app}"
}
export -f flatpak_preview

app="$(
	flatpak list --app --columns=name,application |
		fzf --preview 'flatpak_preview {}' \
			--reverse \
			--cycle \
			--bind change:first \
			--bind esc:cancel+clear-selection \
			--height=100% \
			--border=none \
			--prompt='$ flatpak run ' \
			--no-separator |
		awk -F'\t' '{print $2}'
)"

if [ -z "${app}" ]; then
	exit 1
else
  echo "flatpak run" "${app}" "${@}" >&2
  flatpak run "${app}" "${@}"command
fi

